<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<AssemblyName>ScavMulti</AssemblyName>
		<Product>Multiplayer for Scav Prototype aka Casualties: Unknown (WIP)</Product>
		<Version>1.0.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>ScavMulti</RootNamespace>
		<AssemblyName>$(AssemblyName)-$(Platform)</AssemblyName>
		<Platforms>AnyCPU;x64;x86</Platforms>
	</PropertyGroup>

	<Import Project="../vars.targets" />

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
		<PackageReference Include="BepInEx.Core" Version="5.*" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" PrivateAssets="all" />
		<PackageReference Include="UnityEngine.Modules" Version="2022.3.18" IncludeAssets="compile" />
		<PackageReference Include="MessagePack" Version="3.1.4" />
		<PackageReference Include="MessagePack.ReactiveProperty" Version="3.1.4" />
		<PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />

		<Reference Include="Assembly-CSharp" Publicize="true">
			<HintPath>$(GameAssembliesDir)/Assembly-CSharp.dll</HintPath>
		</Reference>

		<Reference Include="UnityEngine.UI">
			<HintPath>$(GameAssembliesDir)/UnityEngine.UI.dll</HintPath>
		</Reference>

		<Reference Include="Unity.TextMeshPro">
			<HintPath>$(GameAssembliesDir)/Unity.TextMeshPro.dll</HintPath>
		</Reference>

		<ProjectReference Include="../MessagePack.Unity/MessagePack.Unity.csproj" />

	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
	</ItemGroup>

	<PropertyGroup>
		<RequiredFilesToCopy>
			$(AssemblyName).dll;
			$(AssemblyName).pdb;
			MessagePack.dll;
			MessagePack.Unity.dll;
			MessagePack.Annotations.dll;
			System.Buffers.dll;
			System.Memory.dll;
			System.Collections.Immutable.dll;
			System.Runtime.CompilerServices.Unsafe.dll;
			System.Threading.Tasks.Extensions.dll;
			System.Numerics.Vectors.dll;
			Microsoft.Bcl.AsyncInterfaces.dll
		</RequiredFilesToCopy>
	</PropertyGroup>

	<Target Name="CopyOutputDllsToPluginsFolder" AfterTargets="AfterBuild">
		<MakeDir Directories="$(BepInExDir)/plugins/$(PluginDirName)" />
		<CombinePath BasePath="$(OutDir)" Paths="$(RequiredFilesToCopy)">
			<Output TaskParameter="CombinedPaths" ItemName="RequiredFilesToCopy_Combined" />
		</CombinePath>
		<Copy SourceFiles="@(RequiredFilesToCopy_Combined)" DestinationFolder="$(BepInExDir)/plugins/$(PluginDirName)" />
	</Target>
</Project>
